version: "3"
services:
  app :
    build: .
    ports:
      - 5000:5000
    #command: flask run --host=0.0.0.0
    #command: gunicorn -b 0.0.0.0:5000 hello:app --reload
    command: python hello.py
    environment:
      - FLASK_ENV=development
      - FLASK_APP=hello.py
      - PYTHONUNBUFFERED=True
    volumes:
      - ./:/app

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=ivanovd
      - POSTGRES_USER=ivanovd

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080






